const $=s=>document.querySelector(s),heroFilms=['terre','wilding','arbres'].map(id=>FILMS.find(f=>f.id===id));let active=heroFilms[0],category='Tous',opener=null;const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const portrait=f=>'assets/poster-'+f.n+'.jpg';
$('.picks').innerHTML=heroFilms.map((f,i)=>`<button class="pick" data-feature="${f.id}" aria-label="Mettre à la une : ${f.title}" aria-pressed="${i===0}"><img src="assets/${f.image}" alt=""><span>0${i+1}</span></button>`).join('');
function feature(id,animate=true){active=heroFilms.find(f=>f.id===id);const f=active;$('#scene').innerHTML=`<img src="assets/${f.image}" alt="Photogramme de ${f.title}, source Jupiter Films">`;$('#hero-content').innerHTML=`<div class="eyebrow"><span class="signal"></span>${f.cat.toUpperCase()} <span>/ DOCUMENTAIRE</span></div><h1 class="${f.id==='arbres'?'long':''}">${f.id==='terre'?'Toucher<br>terre':f.id==='wilding'?'Wilding':'L’intelligence<br>des arbres'}</h1><div class="metadata"><span>${f.year}</span><i>·</i><span>${f.duration}</span><i>·</i><span>${f.language}</span><span class="format">FILM</span></div><p class="intro">${f.intro}</p><div class="actions"><button class="primary" data-film="${f.id}">Découvrir le film <span>↗</span></button><button class="secondary" data-trailer="${f.id}">▷ &nbsp; Bande-annonce</button></div>`;document.querySelectorAll('.pick').forEach(b=>b.setAttribute('aria-pressed',b.dataset.feature===id));if(animate&&!reduced()){document.querySelectorAll('#scene img,#hero-content').forEach(el=>el.animate([{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:320,easing:'cubic-bezier(.2,.65,.3,1)'}))}}
const normalize=t=>t.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function populate(){const query=normalize($('#search').value.trim());const films=FILMS.filter(f=>(category==='Tous'||f.cat===category)&&normalize(f.title+' '+f.sub+' '+f.director+' '+f.cat).includes(query));$('#posters').innerHTML=films.length?films.map(f=>`<button class="film" data-film="${f.id}" aria-label="Découvrir ${f.title}${f.sub?' : '+f.sub:''}"><span class="art"><img src="${portrait(f)}" alt="Affiche de ${f.title}"><span class="reveal"><span>↗</span></span></span><strong>${f.title}</strong><small>${f.year} &nbsp;·&nbsp; ${f.duration} &nbsp;·&nbsp; ${f.cat}</small></button>`).join(''):'<div class="empty">Aucun film dans cette sélection. Essayez un autre mot ou une autre catégorie.</div>';$('.result-status').textContent=query||category!=='Tous'?films.length+' film'+(films.length>1?'s':'')+' dans cette sélection':'';$('#posters').scrollLeft=0}
function open(html){if(!$('dialog').open)opener=document.activeElement;$('#dialog-content').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();$('dialog').scrollTop=0;document.body.style.overflow='hidden';$('.close').focus();if(!reduced())$('dialog').animate([{opacity:0,transform:'translateY(18px) scale(.98)'},{opacity:1,transform:'none'}],{duration:240,easing:'ease-out'})}
function film(id,trailer=false){const f=FILMS.find(f=>f.id===id);open(`${f.image?`<img class="dialog-photo" src="assets/${f.image}" alt="Photogramme de ${f.title}">`:''}<div class="dialog-body"><span class="eyebrow">${f.cat.toUpperCase()}</span><h2 id="dialog-title">${f.title}${f.sub?'<br><small>'+f.sub+'</small>':''}</h2><div class="metadata">${f.director} · ${f.year} · ${f.duration}</div>${trailer?'<h3>Bande-annonce — aperçu d’interface</h3><p class="synopsis">Cette démo ne lance aucune vidéo. L’emplacement est prévu ici pour découvrir le film sans compte, après vérification de la bande-annonce et de son intégration.</p>':`<div class="actions"><button class="primary" data-info="offer">S’abonner · 80 €/an</button><button class="secondary" data-trailer="${f.id}">▷ Bande-annonce</button></div><h3>L’histoire du film</h3><div class="synopsis">${f.paragraphs.map(p=>'<p>'+p+'</p>').join('')}</div>`}<p class="note">Synopsis et images : <a href="https://www.jupiter-films.com/${f.source}" target="_blank" rel="noopener">Jupiter Films ↗</a>. Accroches courtes proposées pour la démo. Aucun lecteur intégré.</p></div>`)}
function info(type){const content={offer:['Tous les films. Toute une année.','<p class="synopsis">Un abonnement de <strong>80 € par an</strong> pour accéder à l’ensemble du catalogue. Les DVD restent vendus séparément.</p><p class="note">Démo visuelle uniquement : aucune souscription et aucun paiement. Modalités de renouvellement, territoires et droits de diffusion à valider.</p>'],dvd:['Le cinéma, aussi en DVD.','<p class="synopsis">Les éditions physiques restent disponibles dans une boutique distincte de l’abonnement. Ce parcours n’est pas développé dans cette démo d’une seule page.</p><p class="note">Aucun panier ni achat ici.</p>'],about:['Une page pour juger la direction.','<p class="synopsis">Une entrée photographique, un catalogue visible sans détour et une lecture qui s’ouvre sans quitter la sélection. Ce nouvel essai remplace le langage éditorial du précédent : typographie sans empattements, contraste plus franc, accent orangé et commandes plus compactes.</p><p class="note">Référence Apple TV France visitée et observée le 14 septembre 2026 : continuité image / interface et découverte dense. Images publiques Jupiter conservées avec leurs titres incorporés ; masters propres nécessaires avant production. Six films, catégories proposées, pas le catalogue exhaustif. Aucun choix esthétique validé.</p>']};let [title,body]=content[type];open('<div class="dialog-body" style="padding-top:65px"><span class="eyebrow">JUPITER FILMS / DÉMO</span><h2 id="dialog-title">'+title+'</h2>'+body+'</div>')}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.feature)feature(b.dataset.feature);if(b.dataset.film)film(b.dataset.film);if(b.dataset.trailer)film(b.dataset.trailer,true);if(b.dataset.info)info(b.dataset.info);if(b.dataset.cat){category=b.dataset.cat;document.querySelectorAll('[data-cat]').forEach(x=>x.setAttribute('aria-pressed',x===b));populate()}});
$('.close').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>{document.body.style.overflow='';opener?.focus({preventScroll:true})});$('dialog').addEventListener('click',e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('dialog').close()}});$('dialog').addEventListener('keydown',e=>{if(e.key==='Tab'){const nodes=[...$('dialog').querySelectorAll('button,a[href],input')].filter(n=>n.getClientRects().length);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0].focus()}}});
$('#search-toggle').onclick=()=>{$('.searchbox').hidden=false;$('#films').scrollIntoView({behavior:reduced()?'instant':'smooth'});$('#search').focus({preventScroll:true})};$('#search').oninput=populate;$('#search-close').onclick=()=>{$('.searchbox').hidden=true;$('#search').value='';populate();$('#search-toggle').focus()};
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches)document.getAnimations().forEach(a=>a.cancel())});
feature('terre',false);populate();
